### ISSUE TITLE
 MPEGMode is not defined (from Lame.js)

### ISSUE THREAD

**Issue by EdouardLauret** [cstoquer/audio-encoder#14]
Hi there, 

the encoder to mp3 doesn't work anymore.

Here is my code : 
```javascript

import encode from 'audio-encoder';

export const bufferToMp3 = (buffer) => {
        return new Promise((res, rej) => {
            encode(buffer, 320, null, blob => res(blob));
        })
    }
```

An error is thrown : 
```
Lame.js:135 Uncaught (in promise) ReferenceError: MPEGMode is not defined
    at lame_init_old (Lame.js:135:1)
    at Lame.lame_init (Lame.js:229:1)
    at new Mp3Encoder (index.js:100:1)
    at encodeMp3 (encodeMp3.js:49:1)
```

**Comment by MrAlekhin** [comment]
having the same error 👍

**Comment by igorski** [comment]
This is indeed quite broken, version 1.0.2 of audio-encoder is stable. Seems the problem comes from the [lamejs](https://github.com/zhuker/lamejs/issues/86) dependency (apparently 1.2.0 of lamejs still works).

**Comment by joehinkle11** [comment]
1.2.0 works as well for me.

`"audio-encoder": "1.0.2",`

in your package.json

**Comment by yanickrochon** [comment]
`audio-encoder@1.0.2` still gives me the same MPEGMode is not defined.
